package com.simplefileserver.mapper;

import com.simplefileserver.entity.Remote;
import com.simplefileserver.entity.RemoteExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RemoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    long countByExample(RemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int deleteByExample(RemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int deleteByPrimaryKey(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int insert(Remote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int insertSelective(Remote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    List<Remote> selectByExample(RemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    Remote selectByPrimaryKey(String filename);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") Remote record, @Param("example") RemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int updateByExample(@Param("record") Remote record, @Param("example") RemoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int updateByPrimaryKeySelective(Remote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remote
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    int updateByPrimaryKey(Remote record);
}