package com.simplefileserver.entity;

import java.util.Date;

public class File {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.filename
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.time
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.filename
     *
     * @return the value of file.filename
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.filename
     *
     * @param filename the value for file.filename
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.time
     *
     * @return the value of file.time
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.time
     *
     * @param time the value for file.time
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}