package com.simplefileserver.entity;

public class Remote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote.filename
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote.url
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote.filename
     *
     * @return the value of remote.filename
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote.filename
     *
     * @param filename the value for remote.filename
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote.url
     *
     * @return the value of remote.url
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote.url
     *
     * @param url the value for remote.url
     *
     * @mbg.generated Thu Feb 27 11:38:02 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}