package com.simplefileserver.entity;

import java.util.Date;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.filename
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.ip
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column request.time
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.filename
     *
     * @return the value of request.filename
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.filename
     *
     * @param filename the value for request.filename
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.ip
     *
     * @return the value of request.ip
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.ip
     *
     * @param ip the value for request.ip
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column request.time
     *
     * @return the value of request.time
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column request.time
     *
     * @param time the value for request.time
     *
     * @mbg.generated Wed Jan 15 18:14:04 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }
}